name: tsi
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py311h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.4.1=0
  - cuda-version=11.8=hcce14f8_3
  - cudatoolkit=11.8.0=h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.8=py311h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.13.3=h4a9f257_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipython=8.25.0=py311h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.6.0=py311h06a4308_0
  - jupyter_core=5.7.2=py311h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.5.1=hffd6297_1
  - libtorch=2.6.0=cpu_mkl_h881e62d_106
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.17=h5eee18b_0
  - opentelemetry-api=1.37.0=py311h06a4308_0
  - pip=24.0=py311h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h5eee18b_2
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tbb-devel=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchtriton=2.3.1=py311
  - torchvision=0.15.2=cuda118py311h4cc2eb7_0
  - tornado=6.4.1=py311h5eee18b_0
  - traitlets=5.14.3=py311h06a4308_0
  - typing_extensions=4.11.0=py311h06a4308_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - aesara==2.9.3
      - alphashape==1.3.1
      - altair==5.3.0
      - altair-data-server==0.4.1
      - altair-saver==0.5.0
      - altair-viewer==0.4.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - arviz==0.18.0
      - astro-brutus==0.8.3
      - astropy==6.1.1
      - astropy-iers-data==0.2024.6.17.0.31.35
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.2.0
      - autograd==1.6.2
      - babel==2.16.0
      - bayesflow==1.1.6
      - beautifulsoup4==4.12.3
      - bilby==2.4.0
      - bilby-cython==0.5.3
      - bilby-pipe==1.4.2
      - bleach==6.2.0
      - blosc2==3.0.0
      - cachetools==5.3.3
      - catboost==1.2.5
      - certifi==2024.6.2
      - cffi==1.16.0
      - click==8.1.7
      - click-log==0.4.0
      - cloudpickle==3.0.0
      - comm==0.2.2
      - configargparse==1.7
      - cons==0.4.6
      - contourpy==1.2.1
      - corner==2.2.3
      - cryptography==44.0.0
      - cycler==0.12.1
      - cython==3.0.10
      - dask==2024.6.0
      - dateparser==1.2.1
      - debugpy==1.8.1
      - deepdish==0.3.7
      - defusedxml==0.7.1
      - deneb==1.0.1
      - descartes==1.1.0
      - diffeqtorch==1.0.0
      - dingo-gw==0.7.0
      - distributed==2024.6.0
      - dm-tree==0.1.8
      - dqsegdb2==1.3.0
      - dustmaps==1.0.14
      - dynesty==2.1.5
      - elfi==0.8.7
      - emcee==3.1.6
      - entrypoints==0.4
      - etuples==0.3.9
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - filelock==3.15.1
      - flatbuffers==24.3.25
      - flatlatex==0.15
      - fonttools==4.53.0
      - fqdn==1.5.1
      - fsspec==2024.6.0
      - future==1.0.0
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glasflow==0.4.1
      - google-auth==2.30.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - gpy==1.13.1
      - greenlet==3.0.3
      - grpcio==1.64.1
      - gwdatafind==1.2.0
      - gwosc==0.7.2
      - gwpy==3.0.12
      - h11==0.14.0
      - h5netcdf==1.3.0
      - h5py==3.11.0
      - healpy==1.17.1
      - httpcore==1.0.6
      - httpx==0.27.2
      - igwn-auth-utils==1.1.1
      - igwn-segments==2.0.0
      - importlib-metadata==7.1.0
      - ipykernel==6.29.4
      - ipyparallel==8.8.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jabbar==0.0.16
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - julia==0.6.2
      - jupyter==1.1.1
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - keras==2.15.0
      - kiwisolver==1.4.5
      - lalsuite==7.25.1
      - libclang==18.1.1
      - ligo-gracedb==2.13.0
      - ligo-segments==1.4.0
      - ligotimegps==2.0.1
      - llvmlite==0.43.0
      - locket==1.0.0
      - logical-unification==0.4.6
      - lscsoft-glue==4.0.0
      - mako==1.3.9
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - minikanren==1.0.3
      - mistune==3.0.2
      - ml-dtypes==0.3.2
      - mpld3==0.5.10
      - msgpack==1.0.8
      - multipledispatch==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - ndindex==1.9.2
      - networkx==3.3
      - nflows==0.14
      - notebook==6.4.12
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numdifftools==0.9.41
      - numexpr==2.10.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - outcome==1.3.0.post0
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - paramz==0.9.6
      - parso==0.8.4
      - partd==1.4.2
      - patsy==1.0.1
      - pegasus-wms-api==5.0.9
      - pegasus-wms-common==5.0.9
      - pesummary==1.3.4
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.2
      - plotly==5.22.0
      - portpicker==1.6.0
      - progressbar2==4.5.0
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.47
      - protobuf==4.25.3
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyabc==0.12.13
      - pyabcranger==0.0.72
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycbc==2.7.2
      - pycondor==0.6.0
      - pycparser==2.22
      - pyerfa==2.0.1.4
      - pyfftw==0.15.0
      - pygam==0.10.1
      - pygments==2.18.0
      - pyjwt==2.10.1
      - pykerr==0.1.0
      - pyknos==0.16.0
      - pymc==5.17.0
      - pyopenssl==25.0.0
      - pyparsing==3.1.2
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytensor==2.25.5
      - python-graphviz==0.20.3
      - python-json-logger==2.0.7
      - python-ligo-lw==1.8.3
      - python-utils==3.9.1
      - pytz==2025.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - redis==5.0.6
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.18.1
      - rpy2==3.5.4
      - rsa==4.9
      - rtree==1.2.0
      - safe-netrc==1.0.1
      - sbi==0.25.0
      - sbibm==1.1.0
      - scikit-learn==1.5.0
      - scipy==1.11.4
      - scitokens==1.8.1
      - seaborn==0.12.2
      - selenium==4.21.0
      - send2trash==1.8.3
      - setuptools==75.8.0
      - shapely==2.0.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sqlalchemy==2.0.30
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - stellarcd==0.0.1
      - sympy==1.13.1
      - tables==3.10.2
      - tblib==3.0.0
      - tenacity==8.4.1
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.0
      - tensorflow-probability==0.23.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - toolz==0.12.1
      - torch==2.5.1
      - torchdiffeq==0.2.5
      - tqdm==4.66.4
      - trimesh==4.4.1
      - trio==0.25.1
      - trio-websocket==0.11.1
      - triton==3.1.0
      - tsi==0.0.1
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - tzlocal==5.2
      - uri-template==1.3.0
      - urllib3==2.2.2
      - vega-datasets==0.9.0
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.14
      - wrapt==1.14.1
      - wsproto==1.2.0
      - xarray==2024.6.0
      - xarray-einstats==0.7.0
      - xgboost==2.0.3
      - zict==3.0.0
      - zipp==3.19.2
      - zuko==1.3.0
prefix: /home/export/jcarzon/anaconda3/envs/tsi
